### ISSUE TITLE
OsmAnd cloud backup without subscription does not work despite mentioned otherwise in #191.

### ISSUE THREAD

**Issue by dreirund** [osmandapp/web#193]
I have [OsmAnd~ on Android, full featured version 4.5.8 from f-droid](https://f-droid.org/packages/net.osmand.plus/).

As an answer of my feature request #191 it was stated that OsmAnd cloud backup should work without registration:

> *[Basic OsmAnd Cloud, is available for free starting 4.5 release without any subscription.](https://github.com/osmandapp/web/issues/191#issuecomment-1682472185)*

But it does not. Nevertheless issue #191 was closed as completed. So I open a new issue, now as a bug report and not a feature request, here, because the behaviour is different than stated.

I registered a completely new OsmAnd cloud account from within that OsmAnd installation.

I have configured OsmAnd to backup only Settings.

When I want to sync, it fails with a popup "No valid subscription present" and the text

> **Expired subscription**  
> Your OsmAnd Pro subscription is expired,  
> renew it to use backup. You can still restore  
> data from the Cloud.

Below screenshots of the message and configuration:

---

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/web/assets/1590519/8e7245ce-465d-46ab-a509-05af973910b8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/web/assets/1590519/ef54d5dd-35b1-44b5-a23d-036635f2df96"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/web/assets/1590519/37407aba-6230-46d4-8edb-0c9ea4e151e6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/web/assets/1590519/1506f628-6619-4074-a628-ef7ef727dfb3"  width="300" height="auto"/> </td>
  </tr>
</table>

---

Regards!

**Comment by vshcherb** [comment]
Try logout / login once again.

**Comment by dreirund** [comment]
> Try logout / login once again.

I have tried before, and now after your advice I tried again. (Logout/ Login, without deleting the account/ creating a new account.)

Problem persists.

**Comment by vshcherb** [comment]
You can try nightly build https://download.osmand.net/latest-night-build/OsmAnd-default.apk and check if it persists

**Comment by dreirund** [comment]
> You can try nightly build
> https://download.osmand.net/latest-night-build/OsmAnd-default.apk and
> check if it persists

That would require me uninstalling the app because the signing key will
be different, which will involve some work to backup and restore data
and downloaded maps, and I am not sure if the downloaded maps and
configured raster maps will be easily re-detected.

Before I do this, I ask you:

Have you tested with a fresh installation of the f-droid build of
OsmAnd? If not, can you first test to reproduce or not-reproduce the
issue I observe?

**Comment by vshcherb** [comment]
It's a nightly build with different package I don't think you need to uninstall

**Comment by dreirund** [comment]
> *You can try nightly build https://download.osmand.net/latest-night-build/OsmAnd-default.apk and check if it persists*

With the nightly build of "default" OsmAnd it works.

I then checked again with the full build of OsmAnd~, logged out and re-logged in, and activated only "Profiles" and "OsmAnd settings". Problem persists.

**Comment by dreirund** [comment]
Any news on this? Can you reproduce the issue with ["OsmAnd~" from f-droid](https://f-droid.org/packages/net.osmand.plus/), have you tested?

**Comment by dmpr0** [comment]
@dreirund F-Droid version is provided by F-Droid community. 
Please try to use [nightly](https://download.osmand.net/latest-night-build/OsmAnd-default.apk) version provided by OsmAnd.

**Comment by dreirund** [comment]
On Thu, 07 Sep 2023 03:45:25 -0700, Dmytro Prodchenko
***@***.***> wrote:

> @dreirund F-Droid version is provided by F-Droid community. 
> Please try to use
> [nightly](https://download.osmand.net/latest-night-build/OsmAnd-default.apk)
> version provided by OsmAnd.

Will this auto-update?

**Comment by dmpr0** [comment]
> On Thu, 07 Sep 2023 03:45:25 -0700, Dmytro Prodchenko ***@***.***> wrote: @dreirund F-Droid version is provided by F-Droid community. Please try to use [nightly](https://download.osmand.net/latest-night-build/OsmAnd-default.apk) version provided by OsmAnd.
> Will this auto-update?

No, but if you enable **OsmAnd Development** plugin you will can update it manually thru **Menu** – **Build**.

**Comment by dreirund** [comment]
> Please try to use [nightly](https://download.osmand.net/latest-night-build/OsmAnd-default.apk) version provided by OsmAnd

https://download.osmand.net/latest-night-build/OsmAnd-default.apk is not the full-featured version.

But what is with https://download.osmand.net/latest-night-build/OsmAnd-android-full-arm64.apk? It also identifies itself as OsmAnd~, the same as the f-droid version.

*(I did not install https://download.osmand.net/latest-night-build/OsmAnd-android-full-arm64.apk in order not to loose my downloaded maps -- the only way to have the maps downloaded to SD-Card (adopted) is for me to have the App installed on SD-Card and download maps to App storage, "External storage" the App reports only the free space of the internal storage)*

**Comment by dreirund** [comment]
> *F-Droid version is provided by F-Droid community.*

Note: Related issue report at f-droid: [&nearr;&hairsp;](here).

> *what is with https://download.osmand.net/latest-night-build/OsmAnd-android-full-arm64.apk? It also identifies itself as OsmAnd~, the same as the f-droid version, but is distributed by you.*

**Comment by dmpr0** [comment]
* [OsmAnd-android-full-arm64.apk](https://download.osmand.net/latest-night-build/OsmAnd-android-full-arm64.apk) Is full-featured version but it probably has the same package name as F-Droid version, `net.osmand.plus`.
* [OsmAnd-default.apk](https://download.osmand.net/latest-night-build/OsmAnd-default.apk) is a free version, with `net.osmand.dev` package name so it possible to install as separate app

**Comment by dreirund** [comment]
> > F-Droid version is provided by F-Droid community.
> 
> *Note: Related issue report at f-droid: [&nearr;&hairsp;here](https://gitlab.com/fdroid/fdroiddata/-/issues/3074).*

OK, the comments [&nearr;&hairsp;here](https://gitlab.com/fdroid/fdroiddata/-/issues/3074#note_1553186553) and [&nearr;&hairsp;here](https://gitlab.com/fdroid/fdroiddata/-/issues/3074#note_1553435343):

> ***@Licaon_Kter:***  
> *I guess, as all the "subscription" code is based on proprietary Google libs, afaik.*

> ***@yourealwaysbe:***  
> *I probably replaced that with a stub always returning false or something.*

suggest that for OsmAnd cloud backup there is some code based on proprietary Google libraries.

Can you confirm or reject this guess?

If that is true I want to change this issue to a feature request to use only free code for the Cloud backup that does not require any subscription.

Should I make a new issue in [github.com/osmandapp/Osmand/](https://github.com/osmandapp/Osmand/) titled a `[Feature Request]` for it (and close here), or should I leave it open here?

Regards!

**Comment by dreirund** [comment]
Closing as it works per https://gitlab.com/fdroid/fdroiddata/-/issues/3074#note_1660206567.
