### ISSUE TITLE
Stop zooming to extents when enabling favorites or tracks

### ISSUE THREAD

**Issue by Busterama452** [osmandapp/web#246]
Right now, when you turn on a favorite category or a track the map zooms out to the extents of the category or track.  

Can we stop this or at least have an option to disable that behavior.

It's particularly frustrating when you're looking at a map in a particular area and you want to see if any of your favorites are in that area or view a track that passes through there.  When the map zooms out to extents you lose where you were looking and have to browse the map back to that area.

Attached is an example (nope, not attached. GPX file attachments aren't allowed here).  The GPX file I was going to upload is the location of all wildlife watering stations (aka Guzzlers) across the state of Arizona.  If I'm viewing an area of the map and I want to see if there are any guzzlers in that area, I want to just go flip the switch for that category and see the favorites in my map view.  I don't want OSMAND Web to leave the area I'm looking and show me the entire state.

**Comment by DmitryAlexei** [comment]
@Busterama452 you can attach your .gpx  file as .zip or after changing it's extension to .txt

**Comment by Busterama452** [comment]
How about I just upload the GPX file as a TXT and skip the zip part.
[favorites-Guzzlers.txt](https://github.com/osmandapp/web/files/12824970/favorites-Guzzlers.txt)

**Comment by yuriiurshuliak** [comment]
It was reproduced. Upon investigating the web version at https://www.osmand.net/map, enabling any additional track causes the map to automatically zoom in based on the territory of the chosen track.

Expected result: The option to deactivate track and favorites zoom while activating them.

https://github.com/osmandapp/web/assets/127092082/a5a2f3a0-a4a9-4e92-a3f1-19764ab98ebf

**Comment by pawelpbm** [comment]
This literally makes the web app unusable. I have probably 3k favorites spread over area of Poland. Previously when zoomed in, I had no problem of browsing the map with them enabled, as most of them would be outside of my zoomed in area. Now when the zoom-out happens map is extremly laggy (TBH this version is laggy even when enabling folder with like 8 points)

Additional issue I think related to this one, is that when you click favourite and then click back arrow or the close button for the point, map is also zoomed out.

**Comment by Busterama452** [comment]
I agree that the current behavior of zooming to extents make the app unusable.  You lose your place on the map and it does drag down performance having to render all of the favorites.

What would be great is to be able to just not do any zooming at all when enabling a category.  Then, just add a button below the slider button for each favorites category "Zoom out to extents" to allow someone, if they so chose, to zoom all the way out to see all of that category's favorites in the map view.

> This literally makes the web app unusable. I have probably 3k favorites spread over area of Poland. Previously when zoomed in, I had no problem of browsing the map with them enabled, as most of them would be outside of my zoomed in area. Now when the zoom-out happens map is extremly laggy (TBH this version is laggy even when enabling folder with like 8 points)
> 
> Additional issue I think related to this one, is that when you click favourite and then click back arrow or the close button for the point, map is also zoomed out.

**Comment by dmpr0** [comment]
## ToDo

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/web/assets/9365308/cc83beeb-4be0-41de-a2fb-1f1ede45a45a"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Don't move map after taping on **Show on map** action, in track context menu

**Comment by dmpr0** [comment]
# Review
- [ ] Show on map – doesn't work if track visible on the map
