### ISSUE TITLE
Display GPS coords for favourites

### ISSUE THREAD

**Issue by sybrenstuvel** [osmandapp/web#279]
It would be so nice if the map web interface would show coordinates for favourites.

This is what things currently look like:

![image](https://github.com/osmandapp/web/assets/1092128/5872e1b1-75b8-40c5-804a-9d3f8468900f)

In order to have any use for these favourites outside of the Osmand website, it's vital to know where they are on the planet. For example, this is a fave from my "OSM TODO" category, which means I want to add it to OSM. The workflow that Osmand Cloud now almost makes possible is to create the fave on my phone when I'm there, sync to Osmand Cloud, then use the web interface on my laptop to do the final OSM editing.

**Comment by RZR-UA** [comment]
It would be great to access GPS coordinates of Favorite points and Waypoints from their information page.

At the moment you can easily get the coordinates by doing right mouse click and choose "Copy coordinates".

**Comment by vshcherb** [comment]
Going to redesign full context menu soon with this information available
