### ISSUE TITLE
Add OsmAnd "offline" routing provider

### ISSUE THREAD

**Issue by JohnVeness** [osmandapp/web#284]
When troubleshooting routing problems with OsmAnd for Android, it would be useful if osmand.net/map could be used to simulate the "offline" routing algorithm that the mobile app uses, i.e. as another (non-default) provider next to OSRM and OSRM (beta).

**Comment by vshcherb** [comment]
Yes it's possible on https://test.osmand.net/map/?start=48.632909,9.316406&finish=48.680081,10.428772&type=osmand&profile=car#11/48.5816/9.8187 - we're going to switch to fully offline osmand routing this month. Though it will be new type of routing from 4.6 release

**Comment by vshcherb** [comment]
Should be in production
