### ISSUE TITLE
It's not possible to delete a "favorite"

### ISSUE THREAD

**Issue by StarOnDavid** [osmandapp/web#293]
After a click on "DELETE" nothing happens. So it's not possible to delete the Favorite.

<img width="1438" alt="Screenshot 2023-12-11 at 18 22 12" src="https://github.com/osmandapp/web/assets/62537549/7a602878-57a8-4a7b-b9b8-59cd0f100259">

**Comment by DmitryAlexei** [comment]
Please see if you can delete favorite folder this evening or tomorrow
