### ISSUE TITLE
Osmand Live and broken osmbtc.org website

### ISSUE THREAD

**Issue by rugk** [osmandapp/web#310]
> Is that cryptocurrency payout to contributors even still live? If I go to https://osmand.net/osm_live this redirects to https://osmbtc.org/, which has a certificate error and even if that is dismissed for testing, it just serves the usual OSM website.

From https://github.com/osmandapp/OsmAnd/discussions/12187#discussioncomment-8030822

So:
* why this redirect?
* is the domain even valid? If so, certificate error needs fixing.
* is the content of that website the correct one?

**Comment by yuriiurshuliak** [comment]
The current status of this service is that it's unavailable and not functioning.

**Comment by vshcherb** [comment]
Starts are available but for history reason - https://creator.osmand.net/osm_live
