### ISSUE TITLE
Bug in poi categories on the site

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/web#351]
### Description

Starting with the "routes" category, there has been a shift between icons and category names.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/1cd6bde8-dc21-4125-a08f-e3dbbb3ac21f"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

Open the list of categories on the site.

### Actual result

The current state is shown in the screenshot above.

### Expected result

The category name must match the icon.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Already available

**Comment by Nine-Tailed** [comment]
Thanks.
