### ISSUE TITLE
Provide URLs for different sections 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#374]
## Description
Links will allow to bookmark them or share with other users.

### Main pages

- [x] **Weather** – `osmand.net/map/weather`
- [x] **Account** – `osmand.net/map/account`
- [x] **Configure Map** – `osmand.net/map/configure/`
- [x] **Tracks** – `osmand.net/map/mydata/tracks`
- [x] **Favorites** – `osmand.net/map/mydata/favorites`
- [x] **Navigation** – `osmand.net/map/navigate`
- [x] **Settings** – `osmand.net/map/settings`
- [x] **Plan a Route** - `osmand.net/map/plan`
- [x] For current Explore page - `osmand.net/map/search`

### Context menu
https://github.com/osmandapp/OsmAnd-Issues/issues/2467
- [x] If tap on item open new page, change URL to that page.

**Comment by vshcherb** [comment]
# Dev notes
- [ ] If tap on item open new page, change URL to that page.
- [ ] PIN parameter is common to all menu items and is preserved in the URL when navigating between items
- [ ] Navigation parameters can only be displayed in the navigation menu. When route building begins, it switches to map/navigate. During this process, support for old URLs is maintained ( https://test.osmand.net/map/?start=50.731830,7.086730&end=50.730990,7.087470&profile=car#18/50.73149/7.08623)
- [ ] If a transition from the navigation menu to another menu item occurs, the navigation data from the URL is cached and restored upon return.

**Comment by RZR-UA** [comment]
Additionally:

- [ ] check /map/loginForm (how to specify page to load after login? especially in case of login-required actions such as Show regions, etc)

- [ ] check LOGIN_LOGOUT_URL (auto-logout as result of API request)

- [ ] check /map/delete-account

**Comment by dmpr0** [comment]
## Review
- [ ] Browser back doesn't work all the time. 
- [ ] Try to open My Places > Tracks > tap on track. Taping back doesn't change map or UI.
- [ ] Favorites

**Comment by RZR-UA** [comment]
Compatibility problem:

https://test.osmand.net/map/?start=47.497380,19.037180&end=47.229784,18.650196&profile=car&params=car,avoid_motorway,prefer_unpaved,routing:astar_normal_java,noglobalfile#12/47.2622/18.6956

redirects to

https://test.osmand.net/map/navigate/?start=47.497380,19.037180&end=47.229784,18.650196&profile=car#12/47.2622/18.6956

Important part ```params=...``` is lost as the result.

Please think how to fix it.

**Comment by alisa911** [comment]
> Compatibility problem:
> 
> https://test.osmand.net/map/?start=47.497380,19.037180&end=47.229784,18.650196&profile=car&params=car,avoid_motorway,prefer_unpaved,routing:astar_normal_java,noglobalfile#12/47.2622/18.6956
> 
> redirects to
> 
> https://test.osmand.net/map/navigate/?start=47.497380,19.037180&end=47.229784,18.650196&profile=car#12/47.2622/18.6956
> 
> Important part `params=...` is lost as the result.
> 
> Please think how to fix it.

fixed

**Comment by vshcherb** [comment]
- [ ] Separate task for back / forward in Browser

**Comment by alisa911** [comment]
https://github.com/osmandapp/web/pull/446
