### ISSUE TITLE
Occitan language not working on Web Version

### ISSUE THREAD

**Issue by adminieo** [osmandapp/web#382]
### Description

The mobile device map works very well in Occitan.
However, the online map (https://osmand.net/map) remains in French even if you select Occitan in the settings.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/55922444/42b2485c-47e3-42f0-8231-8b3f9da134b3"  width="600" height="auto"/> </th>
  </tr>
</table>

Would be possible to correct this. THANKS

### Steps to reproduce

Refresh screen
And select Occitan again

### Actual result

No effect

### Expected result

Read the map with the words in Occitan, as on the application (pc or mobile)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version: SONOMA 14.4.1
safari


Device model: MACbook Pro M2 2022
Crash-Logs: ?
```

**Comment by dmpr0** [comment]
This setting **Display language** is applied only to UI language.  Currently, Web version doesn't support changing map language.
