### ISSUE TITLE
Unable to use web version with 9000 favorites points (or tracks with more than 5000 points)

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#384]
### How to reproduce
* Import as favorites – [2014 - LIDL Europe.gpx.zip](https://github.com/osmandapp/web/files/15037690/2014.-.LIDL.Europe.gpx.zip)
* Open **Menu** – **Configure Map** – **Favorites**, turn on

### Actual result

* UI and map are lagging
* Unable to Hide this favorites folder due to lagging

### Expected result

* Works without lag because:
* * Points doesn't visible on the map in this moment 
* * Points list doesn't visible on the map at the momment
* Android and iOS works without problem with this file 

**Environment**
OsmAnd Version: Web Test, from 19 Apr 24

**Comment by DmitryAlexei** [comment]
This also applies to tracks. Tracks with more than 5000 points slow down OsmAnd Web.

**Comment by alisa911** [comment]
- [ ] Create custom clustarisation for markers

**Comment by alisa911** [comment]
- [ ] Favorites
- [ ] Tracks points
- [ ] Tracks wpts
