### ISSUE TITLE
Track name is not updated in GPX export xml

### ISSUE THREAD

**Issue by FozzieHi** [osmandapp/web#387]
For example, create a track which initially has the name of `Sat Apr 20 2024`, update the name to `Test`, the name in the GPX file remains `Sat Apr 20 2024`:
```xml
<metadata>
  <name>Sat Apr 20 2024</name>
</metadata>
  ```

I have a fix working locally, which I'll submit a PR with. This is my first time working with OsmAnd though so the fix may not be correct, hence why I created this issue separately.

**Comment by vshcherb** [comment]
To do: when you create a track or edit in Plan Route you want to change name once you save, the tag is updated
