### ISSUE TITLE
Bogous crossing straight lines near the poles on lowest zoom level when isodistance circles are activated.

### ISSUE THREAD

**Issue by dreirund** [osmandapp/web#437]
Ahoj,

when I have isodistance circles enabled, in the lowest zoom level there are bogous crossig straight lines displayed near the poles:

---

![03](https://github.com/user-attachments/assets/6665d077-cd4f-42c6-a1d2-872487b39aa4) ![01](https://github.com/user-attachments/assets/3afe8f2b-ebf5-4cc7-b657-ccf3ad4ea5e0) ![02](https://github.com/user-attachments/assets/f57b81d3-a334-44cb-a062-5bb17a052a94)

---

*(When I scroll south, those lines appear near the south pole.)*

[OsmAnd~ f-droid build](https://f-droid.org/en/packages/net.osmand.plus/) on Android, version [4.7.17](https://f-droid.org/repo/net.osmand.plus_471702.apk):

---

![about](https://github.com/user-attachments/assets/816626fa-f8f9-41cf-afb6-5bb4bd28ed67)

---

**Comment by EugeneZmeuk** [comment]
Please, re-send this issue to https://github.com/osmandapp/OsmAnd/issues

**Comment by dreirund** [comment]
> *Please, re-send this issue to https://github.com/osmandapp/OsmAnd/issues*

Done: [&nearr;&hairsp;here](https://github.com/osmandapp/OsmAnd/issues/20370).
