### ISSUE TITLE
Unexpected behavior when toggling track

### ISSUE THREAD

**Issue by ktiu** [osmandapp/web#441]
Hi, I found the following behavior unexpected and very cumbersome when working with multiple tracks.

**How to reproduce:**

- Create at least one track
- Show tracks in "Local"
- Have at least one track toggled invisible
- Toggle visibility on

**Expected behavior:**

- Shows track in addition to any other visible tracks
- Stays in track overview

**Actual behavior:**

- Jumps to single track interface
- Shows track, but hides all other tracks

**Comment by yuriiurshuliak** [comment]
I couldn't reproduce the issue on my end. There are two options: "Show on map" and "Make track visible." The "Show on map" option zooms in on the selected track and displays a close-up on the map. The "Make track visible" option simply makes the track visible on the map without zooming in.

Could you please clarify if you're referring to the web version [here](https://osmand.net/map/#9/48.5485/22.9958) or the mobile application?

![image](https://github.com/user-attachments/assets/e2660c13-da40-4022-9286-3fdaf9f13b9e)

**Comment by ktiu** [comment]
I'm referring to the web version you linked. I hope this is the correct repo to report the issue?

I'm not seeing the context menu you captured, I'm refering to this blue toggle:

![image](https://github.com/user-attachments/assets/f3bd3d49-d180-49d6-a793-0d991edd9981)

**Comment by vshcherb** [comment]
Plan route will be redesigned hopefully soon. It's now an old version and yes it has inconsistencies with already redesigned Route section
