### ISSUE TITLE
Web POI Filtering  issue

### ISSUE THREAD

**Issue by suphler** [osmandapp/web#447]
After  unselecting  "parking" in  list  of  POI overlay layer and  press apply  button, parking  POI  still  shown  on  the  map:
![image](https://github.com/user-attachments/assets/23630d8b-4932-4242-be0b-988d727a080f)
(web app installed  as  aplication, browser  google  chrome)

**Comment by EugeneZmeuk** [comment]
@DmitryAlexei , I reproduced it for osmand.net/map

**Comment by vshcherb** [comment]
To do: 
1. Fix issue wit select / unselect
2. Hide button Select all - as it won't work as expected too many POIs and hits the limit of POI search . Instead display "Deselect all" active/disabled if there are selected POI
