### ISSUE TITLE
Missing "Menu → Settings → Purchases" menu

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/web#449]
Regarding https://github.com/osmandapp/web/blob/9b77fe76dfff686ef80dd48f261d4aa034cf7f65/main/docs/user/personal/osmand-cloud.md?plain=1#L91

I'm hoping to use [osmand start](https://osmand.net/docs/user/personal/osmand-cloud#osmand-start) to sync my favorites between devices, but the directions reference a "purchases" menu that doesn't exist for me. I'm using "OsmAnd~" version 4.7.17 installed from f-droid.

I'm guessing that the feature isn't available because of which app I'm using, or where I installed it. Consider updating the docs to make that clear. Maybe that's what's meant by "You can use this special plan if you have OsmAnd Free or Maps+"

**Comment by blackboxlogic** [comment]
I'm just realizing the f-droid version isn't supported by you, which makes sense that the purchases menu would be missing.

**Comment by dmpr0** [comment]
Hi! To use OsmAnd Start you don't need any purchase, just create account in OsmAnd Cloud using your Android device. Currently, the Web version doesn't support account creation.
