### ISSUE TITLE
Add info about uphill / downhill to the track info

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/web#453]
### Description
The goal of this task is to add info about uphill / downhill to the track info in Navigation mode, as in Plan-a-route tool.

### ToDo
- uphill / downhill info should be added to the "More information tab", that is available when planning a trip in navigation mode.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/d902ec30-c8e0-469e-90e6-7a7981006b94"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/ddc5ccda-d4d6-40bf-b3ca-d80b2db1a964"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th>Web</th>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d36ff748-5418-482c-aacb-0f113d49d202"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/148f9da1-1b90-4442-a646-024879802185"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/c277899f-41ce-4fc9-a138-3959ba210299"  width="300" height="auto"/> </td>
  </tr>
</table>  

- [ ] Uphill is different from Android and iOS
 * * Example – https://osmand.net/map?start=50.436203%2C30.506290&end=50.449860%2C30.523493&profile=pedestrian#14/50.426743/30.517513

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-2-5404646404607042022-y](https://github.com/user-attachments/assets/fe6136e6-36ce-4527-845d-bccc6f784071)

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/afe11b3991ef39ef7062b66625b6a69a9f153510
