### ISSUE TITLE
Hover for POI icons

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#459]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/81bfc4fa-9fbd-46ad-975f-ef2217023392"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show POI name in hover (similar to favourites)

- - -

- [x] Show hover around POI icon in Search results. Similar we do for Explore items. Hover on the list should be visible on the map.

**Comment by DmitryAlexei** [comment]
- [ ] hover should have a blue outline + name 
- [ ] corresponding item in the menu should be highlighted by clicking on a POI
