### ISSUE TITLE
Show parent category name for sub-categories

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#460]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/275b577d-61a4-4583-92e3-cdcefec8b47d"  width="300" height="auto"/> </td>
  </tr>
</table>   

When searching for POI subcategories, there is no way to see parent category or main category name, so next time user can select one of the main category. 

* Show Parent  / Main category on the second line

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/84cb2285-ebbf-4118-be2a-8010ae771da2"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Filters is visible while searching for categories? 

- - - 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/8e4b5ea2-cf47-4fa2-8c2b-04631ecddf3d"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Wrong icons

**Comment by vshcherb** [comment]
- [ ] Diesel fuel station not searchable in Android searchable

**Comment by dmpr0** [comment]
# Review 2

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/158eda7e-b9a0-4132-b324-aefd87627787"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Filters is showing while searching for `toilets`

**Comment by alisa911** [comment]
- [ ] add subtype for all types in the search results (Bio diesel -> Fuel)
- [ ] need to stay in the search only those that are inside 'poi_additional_category', remove from search <poi_additional name="handwashing_soap_yes" tag="handwashing:soap" value="yes"/>
![2024-09-03 12 25 51](https://github.com/user-attachments/assets/cc66c3a3-112c-41a3-abc4-57fa53c887bd)

**Comment by alisa911** [comment]
@ivanPyrohivskyi Objective-C

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/web/web-search#search-line
