### ISSUE TITLE
Streets are shown as Memorial in Explore

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#497]
### How to reproduce
* Open [osmand.net/map/search](https://osmand.net/map/search/#14/50.0870/29.8920)

### Actual result
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/895eef53-8da1-4fe7-941b-6695409de777"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/07c8d932-9778-4ad7-89b3-b74d7eea1c90"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result
- [x] Don't show streets in Explore
- [x] Start show explore points starting from 6 zoom level.

**Change min. visible zoom level for:**
- [x] **sculpture**  >= `14`
- [x] **Commercial landuse** >= `14`
- [x] **shop** >= `14`
- [x] **artwork** >= `14`

**Comment by vshcherb** [comment]
Check that in Europe we see places to visit not objects / persons . If we can do it differently please let me know

**Comment by vshcherb** [comment]
For example we can display **only objects** that have coordinates in wikidata lower than zoom 13-14

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/dbb8ba3f-745f-4c85-b409-a9827559e82f"  width="600" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Unable to tap on photo in area with left / right buttons

**Comment by vshcherb** [comment]
- [ ] Proper parsing for wikimedia meta blocks 
- [ ] DB cache for mediainfo blocks to avoid be blocked (later we can [commonswiki-20240920-pages-articles-multistream.xml.bz2](https://dumps.wikimedia.org/commonswiki/20240920/commonswiki-20240920-pages-articles-multistream.xml.bz2) 74.3 GB)
