### ISSUE TITLE
For basemap search (zoom < 7) - search coordinates and Basemap POI 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#535]
### How to reproduce
* Open https://test.osmand.net/map/search/
* Try to search for ‎`26°04.650′ N, 119°17.509′ E‎`

### Actual result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/64f94278-0c23-4d2d-9ae6-6fa1a7bc9952"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Loading...

### Expected result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3bf3c773-8302-483a-a649-e31d1ce2f018"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Support all coordinates format that present on the Android / iOS app

**Environment**
9.11.24

**Comment by vshcherb** [comment]
1. To implement: It should be very quick search using LocationParser before full search on server side
2. Why it doesn't work if LocationParser is embedded inside full search itself.

**Comment by vshcherb** [comment]
-------------
Basemap section has POI available for search - large cities, towns ...

**Comment by dmpr0** [comment]
# Review 

- [ ] Add possibility to search city on zoom levels > 7. Currently is it hard to find Berlin on 10 zoom level over Tokyo
