### ISSUE TITLE
Feature request: allow to show multiple tracks

### ISSUE THREAD

**Issue by lamisoft-42** [osmandapp/web#558]
In the app I can select any of my recorded tracks to be displayed simultaneously. In the Web interface, I can only select one track. Selecting another one hides the previously selected track.

**Comment by dmpr0** [comment]
Hi!
It already works, you can do it from Menu – Tracks – Tap on 3 dot's menu – Make track visible. You can control all visible tracks in Menu - Configure Map – Tracks.

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/59924500-a8d5-4ee5-8620-ba25968b225d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by lamisoft-42** [comment]
oops, my apologies. I'm pretty certain I did try all options in this menu and couldn't make multiple tracks appear simultatneously, but apparently must have been confused. So thanks for pointing out how to make this work!
\\// Matthias
