### ISSUE TITLE
Website crash after clicking to Explore POI

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/web#607]
## Description

When I click to Explore POI on the map I receive crash

## Steps to reproduce

1. Open Search menu
2. Explore section > Show all (Crash can be at this step too)
3. Choose any Wikimedia POI on the map

## Actual results

<img width="360" alt="image" src="https://github.com/user-attachments/assets/b2863427-801c-4403-8b8d-37969e7b0a82">

**Comment by alisa911** [comment]
Fixed

**Comment by Zirochkabila** [comment]
# Testing 1
Fixed
