### ISSUE TITLE
Show date first in Weather graphs

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#612]
### How to reproduce
* Go to [osmand.net](https://osmand.net/map/weather/)
* Click on Temperature

### Actual result
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/95720ca0-787d-40f7-8304-7a99e7c6aa79"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Month number is shown first, so we always see the same number first each time: 12.10, 12.11, 12.12, 12.13

### Expected result

* Show date first: 10.12, 11.12, 12.12, 13.12.

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by Zirochkabila** [comment]
# Testing 1
Fixed - Date is displayed first
