### ISSUE TITLE
The Explore pins are not visible on the map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#613]
### How to reproduce
* Go to [osmand.net](https://osmand.net/map/search/explore/#13/50.4508/30.4502)
* Click on Search

### Actual result
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/cb8a67b4-3321-4a55-90e2-3c015c947526"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Empty map

### Expected result

* Photo pins

**Comment by Zirochkabila** [comment]
# Testing 1
Fixed - Explore pins are visible on the map after clicking on Search
