### ISSUE TITLE
Bug - search for brand "Сільпо"

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/web#620]
### Description
Follow up for https://github.com/osmandapp/web/issues/597
When searching for Сільпо, the wrong POI is shown among search results.   

### Steps to reproduce
- go to 50.760933, 25.356295
- search for "Ciльпо"
- see, that post office Justin ([link](https://www.openstreetmap.org/node/7020633727#map=18/50.760634/25.357191)) is highlighted as "Ciльпо" (Завокзальный)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/aee89eb0-e174-4054-b1d2-2cfb1fd8d37b"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/792dd7d0-2375-4470-a850-f2ae2f0b0faa"  width="500" height="auto"/> </td>
  </tr>
</table>

### Expected result
- post office Justin shouldn't be shown in search results

**Comment by alisa911** [comment]
This is not a web-related issue. The problem lies in incorrect data on the map.

`'Сільпо (Центр)' [2992], 1 building(s), 0 intersections(s)
				Buildings:
				2
			'Сільпо (Завокзальний)' [2998], 1 building(s), 0 intersections(s)
				Buildings:
				23`
				
Object https://www.openstreetmap.org/node/7020633727#map=19/50.760738/25.356330

**Comment by xmd5a2** [comment]
According to OSM wiki this tagging is rare but correct (https://wiki.openstreetmap.org/wiki/RU:Key:addr:place)
From examples on this page:
```
addr:place=Павильон Урицкого + addr:housenumber=6
```
But there is only 2 objects in Ukraine with tag `addr:place=Сільпо`. Not clear how to solve it.

**Comment by xmd5a2** [comment]
Nodes were removed from OSM

**Comment by Zirochkabila** [comment]
# Testing
Fixed
