### ISSUE TITLE
Wrong sorting order

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/web#626]
### Description
Wrong sorting order for tracks on web when Last modify option is applied

### Steps to reproduce
- open rec folder on web
- make sure, that Last modify option is applied
- see how tracks are sorted
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/2908c173-e3ae-4c01-9a2b-05fe4f336ef7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/13ceb304-39cd-4b7d-b1b8-ef31b029551e"  width="300" height="auto"/> </td>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/eb8411fe-6f81-488a-bc1a-9eeeae2c709a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/c170904d-9317-433e-b742-6b3c0ebe4301"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/85676bfe-1902-44f1-96a9-e0aa04f1542f"  width="300" height="auto"/> </td>
  </tr>
</table>

### Todo
- reproduce and fix that issue

**Comment by Zirochkabila** [comment]
# Testing 1
Fixed

**Comment by Zirochkabila** [comment]
# Testing 1
Fixed
