### ISSUE TITLE
CORS error when editing favorite on web map

### ISSUE THREAD

**Issue by jay3-3** [osmandapp/web#65]
Hello,

While trying to edit a favorite, I click on save and receive this error:  
![Screenshot from 2023-02-25 15-31-29](https://user-images.githubusercontent.com/71341978/221362616-1cce644f-48e4-4d83-b0a1-0fb2956196ad.png)

![Screenshot from 2023-02-25 15-31-37](https://user-images.githubusercontent.com/71341978/221362620-77ef5079-1496-4ec7-b76b-38df53ac4ed6.png)

I am trying to organise a trip and I think osmand can be really helpful but I am new using it and I payed the PRO mostly to use the web version. 

Thank you.

**Comment by vshcherb** [comment]
Fixed
